- hosts: all
  gather_facts: no
  vars: 
  tasks: 
   - name: Verificando Variaveis
     fail: 
       msg: "Defina as variaveis Endereco e nome do servico"
     when: host_addr == '' 

   - name: Configurando Inventário
     add_host:
       name:  "{{host_addr}}"
       group: "inputhosts"

- hosts: inputhosts
  tasks:
    - name: Restart iis server
      win_command: iisreset
