---

- hosts: all
  gather_facts: no
  tasks:
    - name: Task Extra WWW
      win_iis_webapppool:
        name: www.extra.com.br
        state: restarted
      tags: www
    
    - name: Task Extra WWW_C 
      win_iis_webapppool:
        name: www.extra.com.br_c
        state: restarted
      tags: www_c
    
    - name: Task Extra Ponto Retirada
      win_iis_webapppool:
        name: www.extra.com.br_PontoRetirada
        state: restarted
      tags: pontoretirada

...
