---
- hosts: all
  gather_facts: no
  tasks:
    - name: Task Recycle API Marketing PF
      win_iis_webapppool:
        name: marketing.api-pontofrio.com.br
        state: restarted
      tags: mktapipf

    - name: Task Recycle API Marketing V3 PF
      win_iis_webapppool:
        name: marketing.api-pontofrio.com.br_v3
        state: restarted
      tags: mktapiv3pf

...
