---

- hosts: all
  gather_facts: no
  tasks:
    - name: Task Casasbahia WWW
      win_iis_webapppool:
        name: www.casasbahia.com.br
        state: restarted
      tags: www
    
    - name: Task Casasbahia WWW_C 
      win_iis_webapppool:
        name: www.casasbahia.com.br_c
        state: restarted
      tags: www_c
    
    - name: Task Casasbahia Ponto Retirada
      win_iis_webapppool:
        name: www.casasbahia.com.br_PontoRetirada
        state: restarted
      tags: pontoretirada

...
