---
- hosts: all
  gather_facts: no
  tasks:
    - name: Task Recycle API Busca PF
      win_iis_webapppool:
        name: busca.api-pontofrio.com.br
        state: restarted
      tags: buscaapipf

...
