---
- hosts: all
  gather_facts: no
  tasks:
    - name: Task Recycle API Marketing CB
      win_iis_webapppool:
        name: marketing.api-casasbahia.com.br
        state: restarted
      tags: mktapicb

    - name: Task Recycle API Marketing V3 CB
      win_iis_webapppool:
        name: marketing.api-casasbahia.com.br_v3
        state: restarted
      tags: mktapiv3cb

...
