---
- hosts: all
  gather_facts: no
  tasks:
    - name: Task Recycle API Busca CB
      win_iis_webapppool:
        name: busca.api-casasbahia.com.br
        state: restarted
      tags: buscaapicb

...
