---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install Windows Update
    win_updates:
      category_names:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - ServicePacks
        - UpdateRollups
        - Updates
      whitelist:
      - KB4561666
      log_path: C:\wu.txt

...