---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install Windows Update - Some Categories
    win_updates:
      category_names:
        # - 'Application'
        # - 'Connectors'
        - 'CriticalUpdates'
        # - 'DefinitionUpdates'
        # - 'DeveloperKits'
        # - 'FeaturePacks'
        # - 'Guidance'
        - 'SecurityUpdates'
        # - 'ServicePacks'
        # - 'Tools'
        - 'UpdateRollups'
        # - 'Updates'
      log_path: C:\ansible_wu.txt

...